Copyright **`(c)`** 2025 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free under certain conditions — see the [`license`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.


In [27]:
import numpy as np
from icecream import ic
import random

In [18]:
NUM_KNAPSACKS = 3
NUM_ITEMS = 10
NUM_DIMENSIONS = 2

In [341]:
VALUES = np.random.randint(0, 100, size=NUM_ITEMS)
WEIGHTS = np.random.randint(0, 100, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = np.random.randint(
    0, 100 * NUM_ITEMS // NUM_KNAPSACKS, size=(NUM_KNAPSACKS, NUM_DIMENSIONS)
)

In [21]:
CONSTRAINTS

array([[131,  29],
       [322,  74],
       [148, 304]])

In [ ]:
# the solution can be a list of the value = the knapsack and the index = the item.
# so for NUM_KNAPSACK = 3 and NUM_ITEMS = 10 we will have something like [0,1,0,2,0,2,1,2,1,0]
# and because we can leave behind some items, i will add an extra sack for the items that will be ignored.

randomSolution = np.random.randint(0, NUM_KNAPSACKS+1, NUM_ITEMS)
ic(randomSolution)

ic| randomSolution: array([3, 3, 0, 2, 2, 3, 3, 0, 0, 2])


array([3, 3, 0, 2, 2, 3, 3, 0, 0, 2])

In [342]:
ic(CONSTRAINTS)
def isValidSolution(solution):
    currentWeights = np.zeros((NUM_KNAPSACKS, NUM_DIMENSIONS))
    for i in range(NUM_ITEMS):
        if (solution[i] == NUM_KNAPSACKS):  # item was not taken
            continue
        for d in range(NUM_DIMENSIONS):
            currentWeights[solution[i]][d] += WEIGHTS[i][d]
            if (currentWeights[solution[i]][d] > CONSTRAINTS[solution[i]][d]):
                ic(i, currentWeights)
                return False
    ic(currentWeights)
    return True
ic(randomSolution, WEIGHTS)
isValidSolution(randomSolution)

ic| CONSTRAINTS: array([[ 73, 266],
                        [250, 204],
                        [202, 165]])
ic| randomSolution: array([3, 3, 0, 2, 2, 3, 3, 0, 0, 2])
    WEIGHTS: array([[ 8, 23],
                    [23, 10],
                    [42, 32],
                    [32, 21],
                    [43, 55],
                    [89, 72],
                    [64, 18],
                    [54, 72],
                    [68, 58],
                    [ 6, 96]])
ic| i: 7
    currentWeights: array([[96., 32.],
                           [ 0.,  0.],
                           [75., 76.]])


False

In [348]:
def calculateCurrentSolutionValue(solution):
    value = 0
    for i in range(NUM_ITEMS):
        if (solution[i] == NUM_KNAPSACKS):
            continue
        value += VALUES[i]
    return value
ic(calculateCurrentSolutionValue(randomSolution))
ic(randomSolution, VALUES)

ic| calculateCurrentSolutionValue(randomSolution): 309
ic| randomSolution: array([3, 3, 0, 2, 2, 3, 3, 0, 0, 2])
    VALUES: array([95, 16, 47, 53, 85, 20, 25, 25, 18, 81])


(array([3, 3, 0, 2, 2, 3, 3, 0, 0, 2]),
 array([95, 16, 47, 53, 85, 20, 25, 25, 18, 81]))

## TEST PROBLEMS


In [14]:
# Problem 1:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 3
NUM_ITEMS = 20
NUM_DIMENSIONS = 2
VALUES = rng.integers(0, 100, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 100, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(
    0, 100 * NUM_ITEMS // NUM_KNAPSACKS, size=(NUM_KNAPSACKS, NUM_DIMENSIONS)
)

In [15]:
# Problem 2:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 10
NUM_ITEMS = 100
NUM_DIMENSIONS = 10
VALUES = rng.integers(0, 1000, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 1000, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(
    1000 * 2, 1000 * NUM_ITEMS // NUM_KNAPSACKS, size=(NUM_KNAPSACKS, NUM_DIMENSIONS)
)

In [16]:
# Problem 3:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 100
NUM_ITEMS = 5000
NUM_DIMENSIONS = 100
VALUES = rng.integers(0, 1000, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 1000, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(
    1000 * 10, 1000 * 2 * NUM_ITEMS // NUM_KNAPSACKS, size=(NUM_KNAPSACKS, NUM_DIMENSIONS)
)